language: python
python:
  - 2.7
env:
  - DJANGO=Django==1.4.0
  - DJANGO=Django==1.5.0
  - DJANGO=Django==1.6.0
install:
  - pip install $DJANGO
  - pip install mock==1.0.1
  - pip install coverage==3.7.1
  - pip install coveralls==0.4.1
script:
  - coverage run --source=django_test_mixins.py tests.py
after_success:
  coveralls
deploy:
  provider: pypi
  user: wilfredh
  password:
    secure: UN1MvS38y9hvoH6WJIkvvTNa0DdSrpEwYuuMCKDVvAkeg9FVbPIjQl+bWkwAnoLM7iuwdtHsHSRMQ9a+rzpzCHYtRqEmO73XM8glerQSg47+evEIjUIcPmL0NQDLz2yegvx5DLimHvaSooSQDeYyA/9ovTA4P1Yf17Cy/GfRpNg=
  on:
    tags: true
    repo: Wilfred/django-test-mixins
