language: python
python:
  - 2.7
env:
  - DJANGO=Django==1.4.0
  - DJANGO=Django==1.5.0
  - DJANGO=Django==1.6.0
install:
  - pip install $DJANGO
  - pip install mock==1.0.1
script:
  - python tests.py
